version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data   # persiste banco H2 (quando usando jdbc:h2:file:./data/...)
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
