# Data source - H2 arquivo em ./data (persistência entre reinícios do container)
spring.datasource.url=jdbc:h2:file:./data/demo
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console (apenas para dev/homolog)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server
server.port=8080

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=60000
jwt.refresh.expiration=300000 # 1 minuto em milissegundos para testes rápidos
# jwt.expiration=86400000  # 1 dia em milissegundos

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs
