# Devcontainer base com Java 21 + Maven
FROM mcr.microsoft.com/devcontainers/java:0-21

# (Opcional) utilitários
RUN apt-get update && apt-get install -y git curl unzip && rm -rf /var/lib/apt/lists/*
